[package]

name = "hueclient"
version = "0.1.7"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
description = "Rust library for Philips Hue lights"
homepage = "http://github.com/kali/hue.rs"
repository = "http://github.com/kali/hue.rs"
readme = "README.md"
license = "WTFPL"
keywords = [ "Philips", "hue", "light", "bulb" ]

[dependencies]
regex = "0.1.14"
hyper = "0.1.12"
rustc-serialize = "0.2.12"
